// Code generated by "stringer -type Order -linecomment"; DO NOT EDIT.

package joerg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OrderAttack-1]
	_ = x[OrderDefense-2]
}

const _Order_name = "AttackDefense"

var _Order_index = [...]uint8{0, 6, 13}

func (i Order) String() string {
	i -= 1
	if i < 0 || i >= Order(len(_Order_index)-1) {
		return "Order(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Order_name[_Order_index[i]:_Order_index[i+1]]
}
